payload:
# My list
#- DOMAIN-SUFFIX,fumamx.com
- DOMAIN-SUFFIX,we.tl
- DOMAIN-SUFFIX,wetransfer.net
- DOMAIN-SUFFIX,wetransfer.com
- DOMAIN-SUFFIX,88player.top
- DOMAIN-SUFFIX,88kq.cc
- DOMAIN-SUFFIX,88zhibo.cc
- DOMAIN-SUFFIX,sportsteam368.com
- DOMAIN-SUFFIX,sportsteam25.com
- DOMAIN-SUFFIX,toutiaozb.com
- DOMAIN-SUFFIX,dhl.com
- DOMAIN-SUFFIX,5idhl.com
- DOMAIN-SUFFIX,fedex.com
- DOMAIN-SUFFIX,ups.com
- DOMAIN-SUFFIX,cloudfront.net
- DOMAIN-SUFFIX,fusebox.fm
- DOMAIN-SUFFIX,fireside.fm
- DOMAIN-SUFFIX,samsung.com
- DOMAIN-SUFFIX,crashlytics.com
- DOMAIN-SUFFIX,t-mobile.com
- DOMAIN-SUFFIX,ncdn.ec
- DOMAIN-SUFFIX,adtidy.org
- DOMAIN-SUFFIX,amazon
- DOMAIN-SUFFIX,images-na.ssl-images-amazon.com
- DOMAIN-SUFFIX,testflight.apple.com
- DOMAIN-SUFFIX,ess.apple.com
- DOMAIN-SUFFIX,tv.apple.com
- DOMAIN-SUFFIX,podcasts.apple.com
- DOMAIN-SUFFIX,bookkeeper.itunes.apple.com
- DOMAIN-SUFFIX,tello.com
- DOMAIN-SUFFIX,paypal.com
- DOMAIN-SUFFIX,paypalobjects.com
- DOMAIN-SUFFIX,reddit.com
- DOMAIN-SUFFIX,redditstatic.com
- DOMAIN-SUFFIX,redditmedia.com
- DOMAIN-SUFFIX,redd.it
- DOMAIN-SUFFIX,adobe.com
- DOMAIN-SUFFIX,adobe.io
- DOMAIN-SUFFIX,funletu.com
- DOMAIN-SUFFIX,yunso.net
- DOMAIN-SUFFIX,vesselfinder.com
- DOMAIN-SUFFIX,vesselfinder.net
- DOMAIN-SUFFIX,wpengine.com
- DOMAIN-SUFFIX,lencr.org
- DOMAIN-SUFFIX,tmdb.com
- DOMAIN-SUFFIX,tmdb.org
- DOMAIN-SUFFIX,cdn-zlib.sk
- DOMAIN-SUFFIX,fuckfbi.ru
- DOMAIN-SUFFIX,revenuecat.com
- DOMAIN-SUFFIX,bitwarden.com
- DOMAIN-SUFFIX,ddgksf2013.top
- DOMAIN-SUFFIX,touhou.center
- DOMAIN-SUFFIX,touhou.tel
- DOMAIN-SUFFIX,zongyunti.com
- DOMAIN-SUFFIX,subcome.com
- DOMAIN-SUFFIX,cdn8848.com
- DOMAIN-SUFFIX,paofu.cloud
- DOMAIN-SUFFIX,paofusub2.com
- DOMAIN-SUFFIX,adguard.org
- DOMAIN-SUFFIX,adguard.com
- DOMAIN-SUFFIX,adguard-dns.com
- DOMAIN-SUFFIX,adguard-dns.io
- DOMAIN-SUFFIX,linkedin.com
- DOMAIN-SUFFIX,linkedin-ei.com
- DOMAIN-SUFFIX,licdn.com
- DOMAIN-SUFFIX,lnkd.in
- DOMAIN-SUFFIX,apkmirror.com
- DOMAIN-SUFFIX,apkpure.com
- DOMAIN-SUFFIX,androidpolice.com
- DOMAIN-SUFFIX,modyolo.com
- DOMAIN-SUFFIX,iloveimg.com
- DOMAIN-SUFFIX,vectorpea.com
- DOMAIN-SUFFIX,photopea.com
- DOMAIN-SUFFIX,digicert.com
- DOMAIN-SUFFIX,braze.com
- DOMAIN-SUFFIX,braze-images.com
- DOMAIN-SUFFIX,optimizely.com
- DOMAIN-SUFFIX,quantumult.app
- DOMAIN-SUFFIX,chatway.app
- DOMAIN-SUFFIX,speedtest.net
- IP-CIDR,208.54.5.195/32,no-resolve

# IP Detection
- DOMAIN-SUFFIX,2ip.io
- DOMAIN-SUFFIX,abstractapi.com
- DOMAIN-SUFFIX,db-ip.com
- DOMAIN-SUFFIX,findip.net
- DOMAIN-SUFFIX,freeipapi.com
- DOMAIN-SUFFIX,geoapify.com
- DOMAIN-SUFFIX,geojs.io
- DOMAIN-SUFFIX,icanhazip.com
- DOMAIN-SUFFIX,ident.me
- DOMAIN-SUFFIX,ifconfig.co
- DOMAIN-SUFFIX,ifconfig.me
- DOMAIN-SUFFIX,ip.me
- DOMAIN-SUFFIX,ip-api.com
- DOMAIN-SUFFIX,ip.sb
- DOMAIN-SUFFIX,ip2location.com
- DOMAIN-SUFFIX,ip2location.io
- DOMAIN-SUFFIX,ipaddress.my
- DOMAIN-SUFFIX,ipapi.co
- DOMAIN-SUFFIX,ipapi.com
- DOMAIN-SUFFIX,ipapi.is
- DOMAIN-SUFFIX,ipdata.co
- DOMAIN-SUFFIX,ipdetect.com
- DOMAIN-SUFFIX,ipdrak.com
- DOMAIN-SUFFIX,ipfind.com
- DOMAIN-SUFFIX,ipgeolocation.io
- DOMAIN-SUFFIX,ipify.org
- DOMAIN-SUFFIX,ipinfo.co
- DOMAIN-SUFFIX,ipinfo.io
- DOMAIN-SUFFIX,ipinfojson.com
- DOMAIN-SUFFIX,iplocation.io
- DOMAIN-SUFFIX,iplocation.net
- DOMAIN-SUFFIX,ipstack.com
- DOMAIN-SUFFIX,ipwho.is
- DOMAIN-SUFFIX,maxmind.com
- DOMAIN-SUFFIX,myip.com
- DOMAIN-SUFFIX,myip.sb
- DOMAIN-SUFFIX,requestip.com
- DOMAIN-SUFFIX,whatismyip.com
- DOMAIN-SUFFIX,whatismyip.host
- DOMAIN-SUFFIX,whatismyip.net
- DOMAIN-SUFFIX,whatismyipaddress.com
- DOMAIN-SUFFIX,whoer.net
- DOMAIN-SUFFIX,wtfismyip.com

# Ai general rules
- DOMAIN-SUFFIX,api.revenuecat.com
- DOMAIN-SUFFIX,api.statsig.com
- DOMAIN-SUFFIX,browser-intake-datadoghq.com
- DOMAIN-SUFFIX,static.cloudflareinsights.com
- DOMAIN-SUFFIX,algolia.net
- DOMAIN-SUFFIX,auth0.com
- DOMAIN-SUFFIX,cloudflare.com
- DOMAIN-SUFFIX,arkoselabs.com
- DOMAIN-SUFFIX,statsigapi.net
- DOMAIN-SUFFIX,featuregates.org
- DOMAIN-SUFFIX,identrust.com
- DOMAIN-SUFFIX,intercom.io
- DOMAIN-SUFFIX,intercomcdn.com
- DOMAIN-SUFFIX,launchdarkly.com
- DOMAIN-SUFFIX,segment.io
- DOMAIN-SUFFIX,amazonaws.com
- DOMAIN-SUFFIX,wp.com
- DOMAIN-SUFFIX,sentry.io
- DOMAIN-SUFFIX,stripe.com

# Apple AI
- DOMAIN-SUFFIX,apple-relay.cloudflare.com
- DOMAIN-SUFFIX,apple-relay.apple.com
- DOMAIN-SUFFIX,apple-relay.mask.apple-dns.com
- DOMAIN-SUFFIX,apple-relay.fastly-edge.com
- DOMAIN-SUFFIX,apple-relay.akamaized.net
- DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com
- DOMAIN-SUFFIX,cp4.cloudflare.com
- DOMAIN-SUFFIX,smoot.apple.com
- DOMAIN-SUFFIX,guzzoni.apple.com

# OpenAI/ChatGPT
- DOMAIN-SUFFIX,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
- DOMAIN-SUFFIX,openaicomproductionae4b.blob.core.windows.net
- DOMAIN-SUFFIX,production-openaicom-storage.azureedge.net
- DOMAIN-SUFFIX,ai.com
- DOMAIN-SUFFIX,chatgpt.com
- DOMAIN-SUFFIX,livekit.cloud
- DOMAIN-SUFFIX,oaistatic.com
- DOMAIN-SUFFIX,oaiusercontent.com
- DOMAIN-SUFFIX,openai.com
- DOMAIN-SUFFIX,azureedge.net
- DOMAIN-SUFFIX,imgix.net
- DOMAIN-SUFFIX,datadog.pool.ntp.org

# Google
- DOMAIN-SUFFIX,gfiber.com
- DOMAIN-SUFFIX,ggpht.com
- DOMAIN-SUFFIX,gmail.com
- DOMAIN-SUFFIX,goog
- DOMAIN-SUFFIX,google
- DOMAIN-SUFFIX,google.dev
- DOMAIN-SUFFIX,google.com
- DOMAIN-SUFFIX,google.com.hk
- DOMAIN-SUFFIX,googleapis.com
- DOMAIN-SUFFIX,googletagmanager.com
- DOMAIN-SUFFIX,googleusercontent.com
- DOMAIN-SUFFIX,gstatic.com
- DOMAIN-SUFFIX,withgoogle.com
- DOMAIN-SUFFIX,googlevideo.com
- DOMAIN-SUFFIX,gvt1.com
- DOMAIN-SUFFIX,youtube.com
- DOMAIN-SUFFIX,ytimg.com
- DOMAIN-SUFFIX,youtu.be
- DOMAIN-SUFFIX,yt.be

# Netflix
- DOMAIN-SUFFIX,netflix.com.edgesuite.net
- DOMAIN-SUFFIX,fast.com
- DOMAIN-SUFFIX,netflix.com
- DOMAIN-SUFFIX,netflix.net
- DOMAIN-SUFFIX,netflixdnstest0.com
- DOMAIN-SUFFIX,netflixdnstest1.com
- DOMAIN-SUFFIX,netflixdnstest2.com
- DOMAIN-SUFFIX,netflixdnstest3.com
- DOMAIN-SUFFIX,netflixdnstest4.com
- DOMAIN-SUFFIX,netflixdnstest5.com
- DOMAIN-SUFFIX,netflixdnstest6.com
- DOMAIN-SUFFIX,netflixdnstest7.com
- DOMAIN-SUFFIX,netflixdnstest8.com
- DOMAIN-SUFFIX,netflixdnstest9.com
- DOMAIN-SUFFIX,nflxext.com
- DOMAIN-SUFFIX,nflximg.com
- DOMAIN-SUFFIX,nflximg.net
- DOMAIN-SUFFIX,nflxso.net
- DOMAIN-SUFFIX,nflxvideo.net
- IP-CIDR,8.41.4.0/24,no-resolve
- IP-CIDR,23.246.0.0/18,no-resolve
- IP-CIDR,37.77.184.0/21,no-resolve
- IP-CIDR,38.72.126.0/24,no-resolve
- IP-CIDR,45.57.0.0/17,no-resolve
- IP-CIDR,64.120.128.0/17,no-resolve
- IP-CIDR,66.197.128.0/17,no-resolve
- IP-CIDR,69.53.224.0/19,no-resolve
- IP-CIDR,103.87.204.0/22,no-resolve
- IP-CIDR,108.175.32.0/20,no-resolve
- IP-CIDR,185.2.220.0/22,no-resolve
- IP-CIDR,185.9.188.0/22,no-resolve
- IP-CIDR,192.173.64.0/18,no-resolve
- IP-CIDR,198.38.96.0/19,no-resolve
- IP-CIDR,198.45.48.0/20,no-resolve
- IP-CIDR,203.75.84.0/24,no-resolve
- IP-CIDR,207.45.72.0/22,no-resolve
- IP-CIDR,208.75.76.0/22,no-resolve

# Twitch
- DOMAIN-SUFFIX,ext-twitch.tv
- DOMAIN-SUFFIX,jtvnw.net
- DOMAIN-SUFFIX,ttvnw.net
- DOMAIN-SUFFIX,twitch-ext.rootonline.de
- DOMAIN-SUFFIX,twitch.tv
- DOMAIN-SUFFIX,twitchcdn.net

# TikTok
- DOMAIN-SUFFIX,byteoversea.com
- DOMAIN-SUFFIX,ibytedtos.com
- DOMAIN-SUFFIX,ipstatp.com
- DOMAIN-SUFFIX,muscdn.com
- DOMAIN-SUFFIX,musical.ly
- DOMAIN-SUFFIX,tik-tokapi.com
- DOMAIN-SUFFIX,tiktok.com
- DOMAIN-SUFFIX,tiktokcdn.com
- DOMAIN-SUFFIX,tiktokv.com

# Top Blocked Sites
- DOMAIN-SUFFIX,archive.org
- DOMAIN-SUFFIX,android.com
- DOMAIN-SUFFIX,appspot.com
- DOMAIN-SUFFIX,adobedtm.com
- DOMAIN-SUFFIX,ampproject.org
- DOMAIN-SUFFIX,bloomberg.com
- DOMAIN-SUFFIX,bloomberg.cn
- DOMAIN-SUFFIX,daum.net
- DOMAIN-SUFFIX,fastmail.com
- DOMAIN-SUFFIX,firebaseio.com
- DOMAIN-SUFFIX,flickr.com
- DOMAIN-SUFFIX,flipboard.com
- DOMAIN-SUFFIX,heroku.com
- DOMAIN-SUFFIX,id.heroku.com
- DOMAIN-SUFFIX,kik.com
- DOMAIN-SUFFIX,kobo.com
- DOMAIN-SUFFIX,kobobooks.com
- DOMAIN-SUFFIX,macrumors.com
- DOMAIN-SUFFIX,nytstyle.com
- DOMAIN-SUFFIX,pinimg.com
- DOMAIN-SUFFIX,pinterest.com
- DOMAIN-SUFFIX,pscp.tv
- DOMAIN-SUFFIX,resilio.com
- DOMAIN-SUFFIX,smartdnsproxy.com
- DOMAIN-SUFFIX,startpage.com
- DOMAIN-SUFFIX,trustasiassl.com
- DOMAIN-SUFFIX,tvb.com
- DOMAIN-SUFFIX,v2ex.com
- DOMAIN-SUFFIX,vine.co

# Discord
- DOMAIN-SUFFIX,discord.co
- DOMAIN-SUFFIX,discord.com
- DOMAIN-SUFFIX,discord.gg
- DOMAIN-SUFFIX,discord.media
- DOMAIN-SUFFIX,discordapp.com
- DOMAIN-SUFFIX,discordapp.net

# Facebook
- DOMAIN-SUFFIX,facebook.com
- DOMAIN-SUFFIX,fb.com
- DOMAIN-SUFFIX,fb.me
- DOMAIN-SUFFIX,fbcdn.com
- DOMAIN-SUFFIX,fbcdn.net
- IP-CIDR,31.13.24.0/21,no-resolve
- IP-CIDR,31.13.64.0/18,no-resolve
- IP-CIDR,45.64.40.0/22,no-resolve
- IP-CIDR,66.220.144.0/20,no-resolve
- IP-CIDR,69.63.176.0/20,no-resolve
- IP-CIDR,69.171.224.0/19,no-resolve
- IP-CIDR,74.119.76.0/22,no-resolve
- IP-CIDR,103.4.96.0/22,no-resolve
- IP-CIDR,129.134.0.0/17,no-resolve
- IP-CIDR,157.240.0.0/17,no-resolve
- IP-CIDR,173.252.64.0/18,no-resolve
- IP-CIDR,179.60.192.0/22,no-resolve
- IP-CIDR,185.60.216.0/22,no-resolve
- IP-CIDR,204.15.20.0/22,no-resolve

# Github
- DOMAIN-SUFFIX,github.com
- DOMAIN-SUFFIX,github.io
- DOMAIN-SUFFIX,githubapp.com
- DOMAIN-SUFFIX,githubassets.com
- DOMAIN-SUFFIX,githubusercontent.com
- DOMAIN-SUFFIX,githubcopilot.com

# Instagram
- DOMAIN-SUFFIX,cdninstagram.com
- DOMAIN-SUFFIX,instagram.com
- DOMAIN-SUFFIX,instagr.am

# Pixiv
- DOMAIN-SUFFIX,pixiv.net
- DOMAIN-SUFFIX,pximg.net
- DOMAIN-SUFFIX,fanbox.cc

# Twitter
- DOMAIN-SUFFIX,twitter.com
- DOMAIN-SUFFIX,t.co
- DOMAIN-SUFFIX,twimg.com
- DOMAIN-SUFFIX,twimg.co
- DOMAIN-SUFFIX,twimg.org
- DOMAIN-SUFFIX,x.com

# Telegram
- DOMAIN-SUFFIX,tdesktop.com
- DOMAIN-SUFFIX,telegra.ph
- DOMAIN-SUFFIX,telegram.me
- DOMAIN-SUFFIX,telegram.org
- DOMAIN-SUFFIX,telesco.pe
- IP-CIDR,91.108.0.0/16,no-resolve
- IP-CIDR,95.161.64.0/20,no-resolve
- IP-CIDR,109.239.140.0/24,no-resolve
- IP-CIDR,149.154.160.0/20,no-resolve
- IP-CIDR6,2001:67c:4e8::/48,no-resolve
- IP-CIDR6,2001:b28:f23d::/48,no-resolve
- IP-CIDR6,2001:b28:f23f::/48,no-resolve

# Whatsapp
- DOMAIN-SUFFIX,whatsapp.com
- DOMAIN-SUFFIX,whatsapp.net
- DOMAIN-SUFFIX,edge-mqtt.facebook.com
- IP-CIDR,18.194.0.0/15,no-resolve
- IP-CIDR,34.224.0.0/12,no-resolve
- IP-CIDR,54.242.0.0/15,no-resolve
- IP-CIDR,50.22.198.204/30,no-resolve
- IP-CIDR,208.43.122.128/27,no-resolve
- IP-CIDR,108.168.174.0/16,no-resolve
- IP-CIDR,173.192.231.32/27,no-resolve
- IP-CIDR,158.85.5.192/27,no-resolve
- IP-CIDR,174.37.243.0/16,no-resolve
- IP-CIDR,158.85.46.128/27,no-resolve
- IP-CIDR,173.192.222.160/27,no-resolve
- IP-CIDR,184.173.128.0/17,no-resolve
- IP-CIDR,158.85.224.160/27,no-resolve
- IP-CIDR,75.126.150.0/16,no-resolve
- IP-CIDR,69.171.235.0/16,no-resolve

# Line
- DOMAIN-SUFFIX,lin.ee
- DOMAIN-SUFFIX,line-apps.com
- DOMAIN-SUFFIX,line-cdn.net
- DOMAIN-SUFFIX,line-scdn.net
- DOMAIN-SUFFIX,line.me
- DOMAIN-SUFFIX,line.naver.jp
- DOMAIN-SUFFIX,nhncorp.jp
- IP-CIDR,103.2.28.0/24,no-resolve
- IP-CIDR,103.2.30.0/23,no-resolve
- IP-CIDR,119.235.224.0/24,no-resolve
- IP-CIDR,119.235.232.0/24,no-resolve
- IP-CIDR,119.235.235.0/24,no-resolve
- IP-CIDR,119.235.236.0/23,no-resolve
- IP-CIDR,147.92.128.0/17,no-resolve
- IP-CIDR,203.104.128.0/19,no-resolve

# Wikipedia
- DOMAIN-SUFFIX,wikimedia.org
- DOMAIN-SUFFIX,wikipedia.org
- DOMAIN-SUFFIX,wikibooks.org

# Microsoft
- DOMAIN-SUFFIX,aadrm.com
- DOMAIN-SUFFIX,acompli.com
- DOMAIN-SUFFIX,acompli.net
- DOMAIN-SUFFIX,aka.ms
- DOMAIN-SUFFIX,akadns.net
- DOMAIN-SUFFIX,aspnetcdn.com
- DOMAIN-SUFFIX,assets-yammer.com
- DOMAIN-SUFFIX,azure.com
- DOMAIN-SUFFIX,azure.net
- DOMAIN-SUFFIX,azureiotcentral.com
- DOMAIN-SUFFIX,azurerms.com
- DOMAIN-SUFFIX,bing.com
- DOMAIN-SUFFIX,bing.net
- DOMAIN-SUFFIX,bingapis.com
- DOMAIN-SUFFIX,cloudapp.net
- DOMAIN-SUFFIX,cloudappsecurity.com
- DOMAIN-SUFFIX,edgesuite.net
- DOMAIN-SUFFIX,gfx.ms
- DOMAIN-SUFFIX,hotmail.com
- DOMAIN-SUFFIX,live.com
- DOMAIN-SUFFIX,live.net
- DOMAIN-SUFFIX,lync.com
- DOMAIN-SUFFIX,microsoft
- DOMAIN-SUFFIX,microsoft.com
- DOMAIN-SUFFIX,msappproxy.net
- DOMAIN-SUFFIX,msauth.net
- DOMAIN-SUFFIX,msauthimages.net
- DOMAIN-SUFFIX,msecnd.net
- DOMAIN-SUFFIX,msedge.net
- DOMAIN-SUFFIX,msft.net
- DOMAIN-SUFFIX,msftauth.net
- DOMAIN-SUFFIX,msftauthimages.net
- DOMAIN-SUFFIX,msftidentity.com
- DOMAIN-SUFFIX,msidentity.com
- DOMAIN-SUFFIX,msn.com
- DOMAIN-SUFFIX,msocdn.com
- DOMAIN-SUFFIX,msocsp.com
- DOMAIN-SUFFIX,mstea.ms
- DOMAIN-SUFFIX,o365weve.com
- DOMAIN-SUFFIX,oaspapps.com
- DOMAIN-SUFFIX,office.com
- DOMAIN-SUFFIX,office.net
- DOMAIN-SUFFIX,office365.com
- DOMAIN-SUFFIX,officeppe.net
- DOMAIN-SUFFIX,omniroot.com
- DOMAIN-SUFFIX,onedrive.com
- DOMAIN-SUFFIX,onenote.com
- DOMAIN-SUFFIX,onenote.net
- DOMAIN-SUFFIX,onestore.ms
- DOMAIN-SUFFIX,outlook.com
- DOMAIN-SUFFIX,outlookmobile.com
- DOMAIN-SUFFIX,phonefactor.net
- DOMAIN-SUFFIX,public-trust.com
- DOMAIN-SUFFIX,sfbassets.com
- DOMAIN-SUFFIX,sfx.ms
- DOMAIN-SUFFIX,sharepoint.com
- DOMAIN-SUFFIX,sharepointonline.com
- DOMAIN-SUFFIX,skype.com
- DOMAIN-SUFFIX,skypeassets.com
- DOMAIN-SUFFIX,skypeforbusiness.com
- DOMAIN-SUFFIX,staffhub.ms
- DOMAIN-SUFFIX,svc.ms
- DOMAIN-SUFFIX,sway-cdn.com
- DOMAIN-SUFFIX,sway-extensions.com
- DOMAIN-SUFFIX,sway.com
- DOMAIN-SUFFIX,trafficmanager.net
- DOMAIN-SUFFIX,uservoice.com
- DOMAIN-SUFFIX,virtualearth.net
- DOMAIN-SUFFIX,visualstudio.com
- DOMAIN-SUFFIX,windows-ppe.net
#- DOMAIN-SUFFIX,windows.com
- DOMAIN-SUFFIX,windows.net
- DOMAIN-SUFFIX,windowsazure.com
- DOMAIN-SUFFIX,wunderlist.com
- DOMAIN-SUFFIX,yammer.com
- DOMAIN-SUFFIX,yammerusercontent.com
- DOMAIN-SUFFIX,microsoftazuread-sso.com
- DOMAIN-SUFFIX,microsoftonline.com
- GEOIP,GOOGLE
