payload:
# Mylist 
- DOMAIN-SUFFIX,homehardwarecenter.com 
- DOMAIN-SUFFIX,amazon.com 
- DOMAIN-SUFFIX,acehardware.com 
- DOMAIN-SUFFIX,acehardware-vendors.com 
- DOMAIN-SUFFIX,homedepot.com 
- DOMAIN-SUFFIX,lowes.com 
- DOMAIN-SUFFIX,dollargeneral.com

- DOMAIN-SUFFIX,lens-pa.googleapis.com
- DOMAIN-SUFFIX,lens.google.com
- DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com
- DOMAIN-SUFFIX,ogs.google.com
- DOMAIN-SUFFIX,lensfrontend-pa.googleapis.com
- DOMAIN-SUFFIX,clients4.google.com
