payload:
# Mylist 
- DOMAIN-SUFFIX,amp-api.podcasts.apple.com
- DOMAIN-KEYWORD,amazon
- DOMAIN-KEYWORD,walmart
- DOMAIN-KEYWORD,target
- DOMAIN-KEYWORD,homedepot
- DOMAIN-KEYWORD,thd
- DOMAIN-KEYWORD,lowes
- DOMAIN-KEYWORD,costco
- DOMAIN-KEYWORD,acehardware
- DOMAIN-KEYWORD,homehardware
- DOMAIN-KEYWORD,canadiantire
- DOMAIN-KEYWORD,rona
- DOMAIN-KEYWORD,menards
- DOMAIN-KEYWORD,samsclub
- DOMAIN-KEYWORD,bjs
- DOMAIN-KEYWORD,tjx
- DOMAIN-KEYWORD,burlington
- DOMAIN-KEYWORD,dollargeneral
- DOMAIN-KEYWORD,aldi
- DOMAIN-KEYWORD,gamestop
- DOMAIN-KEYWORD,staples
- DOMAIN-KEYWORD,bestbuy
- DOMAIN-KEYWORD,officedepot
- DOMAIN-KEYWORD,kroger
