payload:
# Mylist 
- DOMAIN-SUFFIX,amp-api.podcasts.apple.com
- DOMAIN-KEYWORD,amazon
- DOMAIN-KEYWORD,walmart
- DOMAIN-KEYWORD,target
- DOMAIN-KEYWORD,homedepot
- DOMAIN-KEYWORD,thd
- DOMAIN-KEYWORD,lowes
- DOMAIN-KEYWORD,costco
- DOMAIN-KEYWORD,acehardware
- DOMAIN-KEYWORD,homehardware
- DOMAIN-KEYWORD,canadiantire
- DOMAIN-KEYWORD,rona
- DOMAIN-KEYWORD,menards
- DOMAIN-KEYWORD,samsclub
- DOMAIN-KEYWORD,bjs
- DOMAIN-KEYWORD,tjx
- DOMAIN-KEYWORD,burlington
- DOMAIN-KEYWORD,dollargeneral
- DOMAIN-KEYWORD,aldi
- DOMAIN-KEYWORD,gamestop
- DOMAIN-KEYWORD,staples
- DOMAIN-KEYWORD,bestbuy
- DOMAIN-KEYWORD,officedepot
- DOMAIN-KEYWORD,kroger

# AI General Rules
- DOMAIN-SUFFIX,challenges.cloudflare.com
- DOMAIN-SUFFIX,api.revenuecat.com
- DOMAIN-SUFFIX,api.statsig.com
- DOMAIN-SUFFIX,static.cloudflareinsights.com
- DOMAIN-SUFFIX,algolia.net
- DOMAIN-SUFFIX,auth0.com
- DOMAIN-SUFFIX,arkoselabs.com
- DOMAIN-SUFFIX,statsigapi.net
- DOMAIN-SUFFIX,featuregates.org
- DOMAIN-SUFFIX,identrust.com
- DOMAIN-SUFFIX,intercom.io
- DOMAIN-SUFFIX,intercomcdn.com
- DOMAIN-SUFFIX,launchdarkly.com
- DOMAIN-SUFFIX,stripe.com

# Apple AI
- DOMAIN-SUFFIX,apple-relay.cloudflare.com
- DOMAIN-SUFFIX,apple-relay.apple.com
- DOMAIN-SUFFIX,apple-relay.mask.apple-dns.com
- DOMAIN-SUFFIX,apple-relay.fastly-edge.com
- DOMAIN-SUFFIX,apple-relay.akamaized.net
- DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com
- DOMAIN-SUFFIX,cp4.cloudflare.com
- DOMAIN-SUFFIX,smoot.apple.com
- DOMAIN-SUFFIX,guzzoni.apple.com

# OpenAI/ChatGPT
- DOMAIN-KEYWORD,openai
- DOMAIN-KEYWORD,chatgpt
- DOMAIN-SUFFIX,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
- DOMAIN-SUFFIX,openaicomproductionae4b.blob.core.windows.net
- DOMAIN-SUFFIX,production-openaicom-storage.azureedge.net
- DOMAIN-SUFFIX,ai.com
- DOMAIN-SUFFIX,chatgpt.com
- DOMAIN-SUFFIX,livekit.cloud
- DOMAIN-SUFFIX,oaistatic.com
- DOMAIN-SUFFIX,oaiusercontent.com
- DOMAIN-SUFFIX,openai.com
- DOMAIN-SUFFIX,imgix.net
- DOMAIN-SUFFIX,datadog.pool.ntp.org
- DOMAIN-SUFFIX,oai.com
- DOMAIN-SUFFIX,chat.com
- DOMAIN-SUFFIX,sora.com
- DOMAIN-SUFFIX,hcaptcha.com
- DOMAIN-SUFFIX,turnstile.cloudflare.com
- DOMAIN-SUFFIX,host.livekit.cloud
- DOMAIN-SUFFIX,turn.livekit.cloud
- DOMAIN-SUFFIX,perplexity.ai

# Google AI
- DOMAIN-KEYWORD,gemini
- DOMAIN-KEYWORD,notebooklm
- DOMAIN-SUFFIX,deepmind.com
- DOMAIN-SUFFIX,deepmind.google
- DOMAIN-SUFFIX,generativeai.google
- DOMAIN-SUFFIX,labs.google
- DOMAIN-SUFFIX,accounts.google.com
- DOMAIN-SUFFIX,aistudio.google.com
- DOMAIN-SUFFIX,client-channel.google.com
- DOMAIN-SUFFIX,clients4.google.com
- DOMAIN-SUFFIX,clients6.google.com
- DOMAIN-SUFFIX,makersuite.google.com
- DOMAIN-SUFFIX,studio.workspace.google.com
- DOMAIN-SUFFIX,addons-pa.googleapis.com
- DOMAIN-SUFFIX,alkalimakersuite-pa.googleapis.com
- DOMAIN-SUFFIX,appsgenaiserver-pa.googleapis.com
- DOMAIN-SUFFIX,gateway-pa.googleapis.com
- DOMAIN-SUFFIX,geller-pa.googleapis.com
- DOMAIN-SUFFIX,jnn-pa.googleapis.com
- DOMAIN-SUFFIX,notebooklm-pa.googleapis.com
- DOMAIN-SUFFIX,opa-pa.googleapis.com
- DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com
- DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com
- DOMAIN-SUFFIX,robinfrontend-pa.googleapis.com
- DOMAIN-SUFFIX,securitydomain-pa.googleapis.com
- DOMAIN-SUFFIX,speechs3proto2-pa.googleapis.com
- DOMAIN-SUFFIX,subscriptionsfirstparty-pa.googleapis.com
- DOMAIN-SUFFIX,voilatile-pa.googleapis.com
- DOMAIN-SUFFIX,clientservices.googleapis.com
- DOMAIN-SUFFIX,cloudaicompanion.googleapis.com
- DOMAIN-SUFFIX,content-push.googleapis.com
- DOMAIN-SUFFIX,generativelanguage.googleapis.com
- DOMAIN-SUFFIX,identitytoolkit.googleapis.com
- DOMAIN-SUFFIX,oauth2.googleapis.com
- DOMAIN-SUFFIX,oauthaccountmanager.googleapis.com
- DOMAIN-SUFFIX,speech.googleapis.com
- DOMAIN-SUFFIX,texttospeech.googleapis.com