payload:
# Mylist 
- DOMAIN-SUFFIX,amp-api.podcasts.apple.com
- DOMAIN-KEYWORD,amazon
- DOMAIN-KEYWORD,lowes
- DOMAIN-KEYWORD,homedepot
- DOMAIN-KEYWORD,thd
- DOMAIN-KEYWORD,acehardware
- DOMAIN-KEYWORD,homehardware
- DOMAIN-KEYWORD,dollargeneral
