payload:
  - 'DOMAIN-SUFFIX,homehardwarecenter.com'
  - 'DOMAIN-SUFFIX,amazon.com'
  - 'DOMAIN-SUFFIX,acehardware.com'
  - 'DOMAIN-SUFFIX,acehardware-vendors.com'
  - 'DOMAIN-SUFFIX,homedepot.com'
  - 'DOMAIN-SUFFIX,lowes.com'
  - 'DOMAIN-SUFFIX,dollargeneral.com'